name: Common issue
description: Issue for a generic issue.
body:
  - type: textarea
    attributes:
      label: What is this about?*
      description: A clear and concise description of the problem
    validations:
      required: true
  - type: textarea
    attributes:
      label: Instructions*
      description: Provide steps to reproduce the problem
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional considerations
      description: Provide error logs or another considerations.
  - type: textarea
    attributes:
      label: Images
      description: Relevant images about the issue
      placeholder: Paste or upload your image with a title.
